2018-11-04 22:20:07,364 INFO: Microblog startup [in C:\Users\tmais\Documents\Coding\Python\hello_flask\app\__init__.py:59]
2018-11-04 22:20:21,184 INFO: Microblog startup [in C:\Users\tmais\Documents\Coding\Python\hello_flask\app\__init__.py:59]
2018-11-04 22:23:45,659 INFO: Microblog startup [in C:\Users\tmais\Documents\Coding\Python\hello_flask\app\__init__.py:59]
2018-11-04 22:23:49,879 ERROR: Exception on /reset_password_request [GET] [in C:\Users\tmais\Envs\hello_flask\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\tmais\Envs\hello_flask\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tmais\Envs\hello_flask\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\tmais\Envs\hello_flask\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\tmais\Envs\hello_flask\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\tmais\Envs\hello_flask\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\tmais\Envs\hello_flask\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\tmais\Documents\Coding\Python\hello_flask\app\routes.py", line 112, in reset_password_request
    title='Reset Password', form=form)
  File "C:\Users\tmais\Envs\hello_flask\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "C:\Users\tmais\Envs\hello_flask\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "C:\Users\tmais\Envs\hello_flask\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\tmais\Envs\hello_flask\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\tmais\Envs\hello_flask\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\tmais\Envs\hello_flask\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\tmais\Documents\Coding\Python\hello_flask\app\templates\reset_password_request.html", line 1, in top-level template code
    {% extends base.html %}
  File "C:\Users\tmais\Envs\hello_flask\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'base' is undefined
2018-11-04 22:25:40,876 INFO: Microblog startup [in C:\Users\tmais\Documents\Coding\Python\hello_flask\app\__init__.py:59]
2018-11-04 22:28:54,087 INFO: Microblog startup [in C:\Users\tmais\Documents\Coding\Python\hello_flask\app\__init__.py:59]
